import '../public/css/globals.scss'
import type { Metadata } from 'next'
import {TheInfo} from "@/app/_components/TheInfo";

export const metadata: Metadata = {
  title: 'Буфф',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <TheInfo/>
      </body>
    </html>
  )
}
